### ISSUE TITLE
unclog bathroom sink

### ISSUE THREAD

**Issue by whit537** [catapultpgh/main#52]
The urinal bathroom sink is clogged. We should unclog it! :-)

**Comment by elliottw** [comment]
<img width="942" alt="screen shot 2015-10-30 at 9 21 00 am" src="https://cloud.githubusercontent.com/assets/1633097/10846649/96a9b81e-7ee7-11e5-9e83-1d1c7c082d39.png">

**Comment by whit537** [comment]
:ok_hand:

**Comment by elliottw** [comment]
seems to be fixed

**Comment by whit537** [comment]
:tada:
