### ISSUE TITLE
a bit of unreliability in wireless

### ISSUE THREAD

**Issue by elliottw** [catapultpgh/main#55]

**Comment by whit537** [comment]
I definitely experienced this yesterday, and last time I was in as well.

**Comment by elliottw** [comment]
more unreliable internet today. anyone want to take up the charge?

**Comment by elliottw** [comment]
i think the only way forward is a DSL backup from Verizon (they don't offer Fios in our area yet).

**Comment by zlrth** [comment]
on behalf of catapult, i talked to comcast today. they said there were no outages at least in the past two weeks according to activity on our comcast modem. I asked if they could email me or catapult their reliability data, but i would have needed to be the account-owner. if that data becomes interesting, we can get it when convenient.

the comcast rep alleges no outages. this implies our router(s) have problems. when the internet goes out, is *no one* able to access it? there are two wireless routers and two networks: catapultpgh and catapultpgh 5GHz. if *some people* are able to access the internet (hey wired users!), then one router is flaking. but if no one can access it, we should get a new cable modem and distrust the comcast rep. 

if that doesn't work, comcast offers a wireless router that doesn't cost any extra per-month (though it costs $80 unavoidable installation) that they'd support. i don't know whether it suits our needs yet.

next time i'm here and the internet goes out, i'll drop what i'm doing--probably by necessity--and attend to it. i reckon i'll call them then-and-there.l

**Comment by wearpants** [comment]
Problem is not our modem, it's Comcast upstream, they drop all packets on their core fiber backbone. Basically the whole city and then some goes out. See https://mobile.twitter.com/wearpants/status/672857882065371137/photo/1

**Comment by zlrth** [comment]
oh.

**Comment by wearpants** [comment]
Comcastic!

**Comment by elliottw** [comment]
again today.

**Comment by elliottw** [comment]
I would like someone (not me) to close this issue. I'm trying to let go of responsibility, not take on more!

**Comment by whit537** [comment]
Is there anyone listening here who is willing to take this on? @wearpants? @zlrth? :-)

**Comment by wearpants** [comment]
Ummm, what needs to be done? If this still Comcast, I refer you to
http://bgr.com/2015/12/14/comcast-ceo-brian-roberts-interview/ and wish you
the best of luck in your future packet routing endeavors.

If there's something busted with the local network (ie, behind the cable
modem), happy to look into it, but it'll have to wait until January.

On Tue, Dec 15, 2015 at 1:36 PM, Chad Whitacre <notifications@github.com>
wrote:

> Is there anyone listening here who is willing to take this on? @wearpants
> <https://github.com/wearpants>? @zlrth <https://github.com/zlrth>? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catapultpgh/main/issues/55#issuecomment-164849949>.
>



-- 
Pete Fein | wearpants.org | @wearpants

**Comment by elliottw** [comment]
to help here, i did this: https://github.com/catapultpgh/main/blob/master/network.md
stripped out all the apple stuff. this should also help with:
https://github.com/catapultpgh/main/issues/64
https://github.com/catapultpgh/main/issues/8
https://github.com/catapultpgh/main/issues/62

**Comment by chadwhitacre** [comment]
Seems to have worked?
