### ISSUE TITLE
check out how Enspiral does money

### ISSUE THREAD

**Issue by whit537** [catapultpgh/main#56]
Sounds like what you've been asking for, @elliottw. :-)

> We have a core piece of digital infrastructure called "my.enspiral" - it’s our homemade bank that holds our internal economy. Money can flow between different people and projects in Enspiral Services without ever leaving our collective bank account.
>
 - Story : my.enspiral: how we made our homemade bank legal

https://github.com/enspiral/guides/blob/master/money.md#our-internal-economy

**Comment by elliottw** [comment]
@whit537 sweet!

**Comment by whit537** [comment]
Not seeing a ton of detail, unfortunately ...

**Comment by elliottw** [comment]
no, but i think we're all on the edge of something and it's inspiring to see others pushing forward.

**Comment by whit537** [comment]
Indeed! Context: https://github.com/gratipay/inside.gratipay.com/issues/421.
