### ISSUE TITLE
take Alanna Krause's work on board

### ISSUE THREAD

**Issue by whit537** [catapultpgh/main#57]
Alanna is one of [Enspiral](http://www.enspiral.com/)'s co-founders. I find her work helpful in thinking about leadership in a collaborative society.

"[Inventing a New Organizational Operating System](https://www.youtube.com/watch?v=4ABqCgKi4X0)"

"[No Boss Does Not Mean No Leadership](https://medium.com/enspiral-tales/no-boss-does-not-mean-no-leadership-c4c97c660252)"

"[How to Grow Distributed Leadership](https://medium.com/enspiral-tales/how-to-grow-distributed-leadership-7f6b25f0361c)"

What are some practical take-aways for Catapult?

**Comment by elliottw** [comment]
wow, totally spaced on this. let me spend the weekend...

**Comment by elliottw** [comment]
https://github.com/catapultpgh/main/commit/b96446c0cfdb50eeaafb2102cd852bd931988fd9

**Comment by elliottw** [comment]
sorry if that close was a bit flippant, trying to create a TON of documentation over the next few weeks, so the rough drafts of incorporation info might seem too rough for now.

**Comment by whit537** [comment]
!m @elliottw

**Comment by whit537** [comment]
cc: @adamtylernelson
