### ISSUE TITLE
Clean out kitchen over winter break

### ISSUE THREAD

**Issue by wearpants** [catapultpgh/main#60]
There is food in the cabinets & fridge that has been there *forever* (well over a year). Let's clean out between Christmas & New Year's. Give people the opportunity to label items they want kept (maybe colored tape). I'd do this, but I'll be out of town.

**Comment by elliottw** [comment]
i'm going to remove all food from the kitchen between xmas and new years, so please get your stuff out. Removing all food labels or not.

**Comment by elliottw** [comment]
also removing that toaster oven. i've been cleaning under it weekly, and i can't keep up with the crumbs.

**Comment by chadwhitacre** [comment]
It hasn't been winter for six months. See #80 for next year. ;-)
