### ISSUE TITLE
airport express settings reset, dropped off the network

### ISSUE THREAD

**Issue by elliottw** [catapultpgh/main#62]

**Comment by elliottw** [comment]
reset

**Comment by elliottw** [comment]
still not connecting. removing from catapult

**Comment by elliottw** [comment]
brought in my airport from home, still couldn't reliably connect

**Comment by iamstev** [comment]
I've got one I am not using, I'll take a look at this tomorrow.

**Comment by elliottw** [comment]
i just switched us off the apple kool aid. all good now.
