### ISSUE TITLE
kitchen bugs

### ISSUE THREAD

**Issue by elliottw** [catapultpgh/main#67]

**Comment by elliottw** [comment]
sprayed and cleared out all food stuff over the holiday

**Comment by elliottw** [comment]
moved the toaster oven into purgatory, as it seems like a culprit for storing food stuffs

**Comment by elliottw** [comment]
any updates?

**Comment by whit537** [comment]
Bugs as in insects? Or metaphorical bugs, "problems with the kitchen"?

**Comment by wearpants** [comment]
Baby roaches in the dishwasher again...

**Comment by whit537** [comment]
[Be sure to hide the roaches](https://www.youtube.com/watch?v=yWRDzl1vIms)! Or kill them, as the case may be. :)

**Comment by elliottw** [comment]
another siting... sigh

**Comment by elliottw** [comment]
anyone want to find an exterminator and we can just take the costs out of our rent payments?

**Comment by chadwhitacre** [comment]
We have ant traps that seem to be working. The bugs are definitely "chastened." :)

Keep the sink clean and run the dishwasher!

Reticket if it gets bad again.
