### ISSUE TITLE
hold July, 2016 town hall

### ISSUE THREAD

**Issue by chadwhitacre** [catapultpgh/main#77]
Here we go! 🗼 

In attendance: Cat, Matt, Emily, Phip, Jim, Boyd, Chad.

**Comment by chadwhitacre** [comment]
## Finances

Cat is presenting the finances.

**Comment by chadwhitacre** [comment]
Cat put together charts after last month's meeting and is open to feedback.

**Comment by chadwhitacre** [comment]
We have a goal of building up a cushion of one month's rent. This month is going to look a little different because we paid our quarterly $1,000 coffee subscription. We'll be at about break-even or a little bit in the red as a result. Probably also a double Comcast payment due to weird timing of their billing.

We're more or less on par with income, but final numbers aren't in yet (lots of payments hit at the end of the month).

**Comment by chadwhitacre** [comment]
Cat proposes cost-per-member as a useful additional metric.

**Comment by chadwhitacre** [comment]
Jim asks how we count "members" since that number fluctuates.

**Comment by chadwhitacre** [comment]
Cat suggests that our membership hasn't fluctuated so wildly that an average (over a month or a few) wouldn't be useful.

**Comment by chadwhitacre** [comment]
Emily suggests that "number of desks booked" could be a good proxy.

**Comment by chadwhitacre** [comment]
We've had about 60 individuals (including estimates for people in the offices) using Catapult. Here's the cost-per-member-per-month breakdown:

| $ | item |
| --: | :-- |
| 60.00 | rent |
| 10.00 | utilities |
| 7.00 | supplies |
| 5.00 | housekeeping |
| 5.00 | coffee |
| 3.50 | beer/happy-hour |
| **93.50** | **total** |

**Comment by chadwhitacre** [comment]
What financial reports would be helpful to review each month at the town hall?

**Comment by chadwhitacre** [comment]
Those present like the per-member-per-month breakdown of expenses as a monthly benchmark for individuals to set their giving against.

What's a good way to look at income? Discussing the list published on the board of what everyone is giving ...

**Comment by chadwhitacre** [comment]
The understanding in the room is that anyone who _wants_ access to the details about who pays what can have it. The question is what we're publishing in what ways.

**Comment by chadwhitacre** [comment]
Cat has started publishing an income report based on source and usage categories:
- paypal
  - offices
  - fixed desks
  - flex desks
  - weekly
  - day passes
- gratipay
- cash

The group thinks this is a useful way to report on income (better than a raw list by member—however, we need to make it clear during onboarding that anyone can get the details at any time—the financials stewards are responsible for this).

"We're generally making more money than we're spending, especially for the past three months. Every once in a while we'll have a big coffee payment. If we continue on this trend, we'll hopefully get the cushion that we need, after which we can start considering capital improvements." —Cat

We may perhaps skip August and start meeting on the 2nd Friday so we can look at a full month at a time.

**Comment by chadwhitacre** [comment]
## Lease

The lease question (#74) leads into the question of the formation of an LLC.

Cat and Chad were in an information meeting with Brian, Elliot, and Steve about LLCs.

The ball is in Elliott's court to drive the formation of an LLC.

**Comment by chadwhitacre** [comment]
## Membership and Culture

There is now an info and orientation sheet in the top-right mailbox slot, and out by the bulletin board with a sign. As members we should encourage new faces to take the sheet and have it signed. How do we make sure _existing_ members know about it? Cat posted it on Slack, which reaches many people, though not all. We like the idea of a Pillar of Announcement at the front of the space: #78.

We also like that tours are led by many different people with different personalities (not just "corporate leaders"). How can we incentivize existing members to help with onboarding new members? Perhaps we make the face wall the final step of onboarding, because existing members have an interest in having that as an aid to remembering names. :)

**Comment by chadwhitacre** [comment]
Discussing t-shirts ...

**Comment by chadwhitacre** [comment]
T-shirts reticketed as #79.

**Comment by chadwhitacre** [comment]
## 👽 Space Ops 👾

We're keeping an eye on locking the door and turning the lights off. Autolocking doors will help with this. We're talking about signage and label printers, while also having a central repository of information.

**Comment by whit537** [comment]
Cat.

**Comment by chadwhitacre** [comment]
Considering a Saturday deep clean: #80.

**Comment by chadwhitacre** [comment]
## Ticket Deep Clean

Made a pass through tickets, cleaned up some cruft. Okay!

**Comment by chadwhitacre** [comment]
Anything else?

**Comment by chadwhitacre** [comment]
Okay! Pghuck Catapult!
